# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- iaac_arn

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

# We still need to take the staging directory files and publish it as a build artifact

- task: PublishPipelineArtifact@1
  displayName: 'Publish the Builds directory to the Pipeline'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'sqlapp-secure-artifact'

- task: PublishBuildArtifacts@1
  displayName: 'Publish the Sources to Pipeline'
  inputs:
    TargetPath: '$(Build.SourcesDirectory)/sqlapp/Templates'
    ArtifactName: 'template-artifact'